DROP TABLE IF EXISTS EelJoke;
DROP TABLE IF EXISTS EelPic;
DROP TABLE IF EXISTS CmdLog;
DROP TABLE IF EXISTS Cmd;

create table EelJoke (
    JokeID 			INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	JokeText		TEXT NOT NULL,
	JokeTextLine2	TEXT
);

CREATE TABLE EelPic (
	ImageID		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	CheckSum	TEXT NOT NULL,
	FullPath	TEXT NOT NULL
);

CREATE TABLE Cmd (
	ID			INTEGER NOT NULL PRIMARY KEY,
	Title		TEXT NOT NULL UNIQUE,
	Description	TEXT,
);

CREATE TABLE CmdLog (
	ID			INTEGER NOT NULL PRIMARY KEY,
	Invoker		TEXT NOT NULL,
	TimeStamp	REAL NOT NULL,
	CmdID		INTEGER NOT NULL,
	FOREIGN KEY (ID) REFERENCES Cmd (ID)
);