DROP TABLE IF EXISTS EelJoke;
DROP TABLE IF EXISTS EelPic;
DROP TABLE IF EXISTS Cmd;
DROP TABLE IF EXISTS CmdLog;

CREATE TABLE EelJoke (
    JokeID 			INTEGER PRIMARY KEY AUTOINCREMENT,
	JokeText		TEXT NOT NULL,
	JokeTextLine2	TEXT
);

CREATE TABLE EelPic (
	ImageID		INTEGER PRIMARY KEY AUTOINCREMENT,
	CheckSum	TEXT NOT NULL,
	FullPath	TEXT NOT NULL
);

CREATE TABLE Cmd (
	ID			INTEGER PRIMARY KEY,
	Title		TEXT NOT NULL UNIQUE,
	Description	TEXT
);

CREATE TABLE CmdLog (
	ID			INTEGER PRIMARY KEY AUTOINCREMENT,
	Invoker		TEXT NOT NULL,
	TimeStamp	REAL NOT NULL,
	CmdID		INTEGER NOT NULL,
	FOREIGN KEY (ID) REFERENCES Cmd (ID)
);