/*DROP TABLE IF EXISTS CmdInvokes;
DROP TABLE IF EXISTS Cmds;
DROP TABLE IF EXISTS EelJokes;
DROP TABLE IF EXISTS EelPics;
DROP TABLE IF EXISTS sqlite_sequence;*/

CREATE TABLE "Cmds" (
	"ID"	INTEGER NOT NULL,
	"Title"	TEXT NOT NULL UNIQUE,
	"Description"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE "CmdInvokes" (
	"ID"	INTEGER NOT NULL,
	"Invoker"	TEXT NOT NULL,
	"TimeStamp"	REAL NOT NULL,
	"CmdID"	INTEGER NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE "EelJokes" (
	"JokeID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"JokeText"	TEXT NOT NULL,
	"JokeTextLine2"	TEXT
);
CREATE TABLE "EelPics" (
	"ImageID"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"CheckSum"	TEXT NOT NULL,
	"FullPath"	TEXT NOT NULL
);